[svn] 1.4 release

diff --git a/keychain b/keychain
--- a/keychain
+++ b/keychain
@@ -15,8 +15,8 @@ KEYCHAIN_KEYS=""
 # .ssh-agent file with csh-compatible syntax.
 
 hostname=`uname -n`
-pidf=$HOME/.ssh-agent-${hostname}
-cshpidf=$HOME/.ssh-agent-csh-${hostname}
+pidf=${HOME}/.ssh-agent-${hostname}
+cshpidf=${HOME}/.ssh-agent-csh-${hostname}
 
 for x in ${*}
 do
@@ -31,18 +31,25 @@ done
 # color variables won't be defined if --nocolor is present
 if [ -z "`echo $* | grep '\-\-nocolor'`" ]
 then
+	E="-e"
 	BLUE="\033[34;01m"
 	GREEN="\033[32;01m"
 	OFF="\033[0m"
 	CYAN="\033[01m"
 else
-	unset BLUE GREEN OFF CYAN
+	unset BLUE GREEN OFF CYAN E
 fi
 
 echo
-echo -e "${GREEN}KeyChain ${version}; ${BLUE}http://www.gentoo.org/projects/keychain${OFF}\n Copyright 2001 Gentoo Technologies, Inc.; Distributed under the GPL" 
+echo $E "${GREEN}KeyChain ${version}; ${BLUE}http://www.gentoo.org/projects/keychain${OFF}\n Copyright 2001 Gentoo Technologies, Inc.; Distributed under the GPL" 
 
-mypids=`ps uxw | grep ssh-agent | grep -v grep | awk '{print $2}'` > /dev/null 2>&1
+#This should work under Linux, BSD, others
+mypids=`ps uxw | grep [s]sh-agent | awk '{print $2}'` > /dev/null 2>&1
+if [ $? -ne 0 ]
+then
+	#compensate for Solaris, IRIX (SysV)
+	mypids=`ps -u $USER -f | grep [s]sh-agent | awk '{print $2}'` > /dev/null 2>&1
+fi
 
 if [ -n "`echo $* | grep '\-\-stop'`" ]
 then
@@ -51,14 +58,14 @@ then
  	kill -9 $mypids > /dev/null 2>&1
  	rm -f ${pidf} ${cshpidf} 2> /dev/null
 	#`whoami` (rather than the $LOGNAME var) gives us the euid rather than the uid (what we want)
-	echo -e " ${GREEN}*${OFF} All ssh-agent(s) started by" `whoami` "are now stopped."
+	echo $E " ${GREEN}*${OFF} All ssh-agent(s) started by" `whoami` "are now stopped."
 	echo
 	exit 0
 fi
 
 if [ -n "`echo $* | grep '\-\-help'`" ]
 then
-echo -e Usage: ${CYAN}${0}${OFF} [ ${GREEN}options${OFF} ] ${CYAN}sshkey${OFF} ...
+echo $E Usage: ${CYAN}${0}${OFF} [ ${GREEN}options${OFF} ] ${CYAN}sshkey${OFF} ...
 cat <<EOHELP
 
 Description:
@@ -77,19 +84,19 @@ Description:
  ~/.bash_profile (or ~/.zlogin, in case of zsh):
 
 EOHELP
-echo -e "  ${CYAN}keychain ~/.ssh/id_rsa ~/.ssh/id_dsa"
-echo -e "  . ~/.ssh-agent-\${HOSTNAME}${OFF}"
+echo $E "  ${CYAN}keychain ~/.ssh/id_rsa ~/.ssh/id_dsa"
+echo $E "  . ~/.ssh-agent-\${HOSTNAME}${OFF}"
 echo
-echo -e "  # alt. syntax: . ~/.ssh-agent-\`uname -h\`"
-echo -e "  # note the use of back-quotes (\`) rather than single-quotes (') above."
-echo -e "  # We now append the hostname (\`uname -n\`) to the .ssh-agent filename"
-echo -e "  # for NFS-compatibility."
+echo $E "  # alt. syntax: . ~/.ssh-agent-\`uname -h\`"
+echo $E "  # note the use of back-quotes (\`) rather than single-quotes (') above."
+echo $E "  # We now append the hostname (\`uname -n\`) to the .ssh-agent filename"
+echo $E "  # for NFS-compatibility."
 echo
 echo " You can make keychain work with your csh-compatible shell by adding the"
 echo " following to your .cshrc:"
 echo
-echo -e "  ${CYAN}keychain ~/.ssh/id_rsa ~/.ssh/id_dsa"
-echo -e "  source ~/.ssh-agent-csh-\${HOSTNAME}${OFF}"
+echo $E "  ${CYAN}keychain ~/.ssh/id_rsa ~/.ssh/id_dsa"
+echo $E "  source ~/.ssh-agent-csh-\${HOSTNAME}${OFF}"
 echo
 cat <<EOHELP
  Keychain allows all your apps and cron jobs to use a single ssh-agent process
@@ -97,11 +104,11 @@ cat <<EOHELP
  long-running and will continue to run, even after you have logged out from the
  system.  If you'd like to tighten up security a bit, take a look at the
 EOHELP
-echo -e " ${GREEN}--clear${OFF} option, described below."
+echo $E " ${GREEN}--clear${OFF} option, described below."
 echo
 echo Options:
 echo   
-echo -e " ${GREEN}--clear${OFF}"
+echo $E " ${GREEN}--clear${OFF}"
 echo
 cat <<EOHELP
  Tells keychain to delete all of ssh-agent's host keys.  Typically, This is
@@ -111,7 +118,7 @@ cat <<EOHELP
  when you're logged out.
 EOHELP
 echo
-echo -e " ${GREEN}--noask${OFF}"
+echo $E " ${GREEN}--noask${OFF}"
 echo
 cat <<EOHELP
  This option tells keychain do everything it normally does (ensure ssh-agent is
@@ -120,11 +127,11 @@ cat <<EOHELP
  to ssh-agent.
 EOHELP
 echo
-echo -e " ${GREEN}--nocolor${OFF}"
+echo $E " ${GREEN}--nocolor${OFF}"
 echo
 echo " This option disables color highlighting for non vt-100-compatible terms."
 echo
-echo -e " ${GREEN}--stop${OFF}"
+echo $E " ${GREEN}--stop${OFF}"
 echo
 cat <<EOHELP
  This option tells keychain to stop all running ssh-agent processes, and then
@@ -148,7 +155,7 @@ for x in $mypids
 do
 	if [ "$x" = "$SSH_AGENT_PID" ]
 	then
-		echo -e " ${GREEN}*${OFF} Found existing ssh-agent at PID ${x}"
+		echo $E " ${GREEN}*${OFF} Found existing ssh-agent at PID ${x}"
 		match="yes"
 		break
 	fi
@@ -161,14 +168,13 @@ then
 		kill $mypids > /dev/null 2>&1
 		kill -9 $mypids > /dev/null 2>&1
 	fi
- 	rm -f ${pidf} ${cshpidf} 2> /dev/null
-	echo -e " ${GREEN}*${OFF} All previously running ssh-agent(s) have been stopped."
-	echo -e " ${GREEN}*${OFF} Initializing ${pidf} file..."
-	touch $pidf || ( echo "$0: Cannot create ${pidf}; exiting." 1>&2 && exit 1 )
-	echo -e " ${GREEN}*${OFF} Initializing ${cshpidf} file..."
-	touch $cshpidf || ( echo "$0: Cannot create ${cshpidf}; exiting." 1>&2 && exit 1 )
+	echo $E " ${GREEN}*${OFF} All previously running ssh-agent(s) have been stopped."
+	echo $E " ${GREEN}*${OFF} Initializing ${pidf} file..."
+	>$pidf || { echo "$0: Cannot create ${pidf}; exiting." 1>&2 && exit 1 }
+	echo $E " ${GREEN}*${OFF} Initializing ${cshpidf} file..."
+	>$cshpidf || { echo "$0: Cannot create ${cshpidf}; exiting." 1>&2 && exit 1 }
 	chmod 0600 $pidf $cshpidf
-	echo -e " ${GREEN}*${OFF} Starting new ssh-agent"
+	echo $E " ${GREEN}*${OFF} Starting new ssh-agent"
 	nohup ssh-agent -s | grep -v 'Agent pid' > $pidf
 	. $pidf
 	echo "setenv SSH_AUTH_SOCK $SSH_AUTH_SOCK;" > $cshpidf
@@ -195,7 +201,7 @@ do
  	myid=`ssh-keygen -l -f ${x} 2> /dev/null | cut -f2 -d" "`
  	if [ -z $myid ]
  	then
- 		echo -e " ${GREEN}*${OFF} Skipping key ${BLUE}${x}${OFF}: no such file or directory" 1>&2
+ 		echo $E " ${GREEN}*${OFF} Skipping key ${BLUE}${x}${OFF}: no such file or directory" 1>&2
  		continue
 	fi
 	match=0
@@ -208,10 +214,10 @@ do
 	done
 	if [ $match -ne 1 ]
 	then
-		echo -e " ${GREEN}*${OFF} Adding key ${BLUE}${x}${OFF}..."
+		echo $E " ${GREEN}*${OFF} Adding key ${BLUE}${x}${OFF}..."
 		ssh-add ${x}
 	else
-		echo -e " ${GREEN}*${OFF} Already using key ${BLUE}${x}${OFF}"
+		echo $E " ${GREEN}*${OFF} Already using key ${BLUE}${x}${OFF}"
 	fi
 done
 echo
