[svn] new additions

diff --git a/keychain b/keychain
--- a/keychain
+++ b/keychain
@@ -4,7 +4,7 @@
 # Author: Daniel Robbins <drobbins@gentoo.org>
 # $Header$
 
-version=1.6
+version=1.7
 
 trap "" INT || { echo "$0: warning: trapping signal 2 instead of INT" 1>&2; trap "" 2; }
 PATH="/sbin:/usr/sbin:${PATH}:/usr/ucb"; export PATH;
@@ -12,11 +12,19 @@ KEYCHAIN_KEYS=""
 
 # pidf holds the specific name of the keychain .ssh-agent-myhostname file.
 # We use the new hostname extension for NFS compatibility. cshpidf is the
-# .ssh-agent file with csh-compatible syntax.
+# .ssh-agent file with csh-compatible syntax. lockf is the lockfile, used
+# to serialize the execution of multiple ssh-agent processes started 
+# simultaneously (only works if lockfile from the procmail package is
+# available.
 
 hostname=`uname -n`
-pidf=${HOME}/.ssh-agent-${hostname}
-cshpidf=${HOME}/.ssh-agent-csh-${hostname}
+pidf="${HOME}/.ssh-agent-${hostname}"
+cshpidf="${HOME}/.ssh-agent-csh-${hostname}"
+lockfile="`which lockfile 2>/dev/null`"
+lockf="${HOME}/.keychain-lock-${hostname}"
+
+# perform lock if we have lockfile available
+[ -z "$lockfile" ] || $lockfile -1 "$lockf"
 
 for x in ${@}
 do
@@ -36,18 +44,27 @@ if [ -z "`echo -e`" ]
 then
 	E="-e"	
 	# color variables won't be defined if --nocolor is present
-	if [ -z "`echo ${@} | grep '\-\-nocolor'`" ]
-	then
-		BLUE="\033[34;01m"
-		GREEN="\033[32;01m"
-		OFF="\033[0m"
-		CYAN="\033[01m"
-	fi
+fi
+if [ -z "`echo ${@} | grep '\-\-nocolor'`" ]
+then
+	BLUE="\033[34;01m"
+	GREEN="\033[32;01m"
+	OFF="\033[0m"
+	CYAN="\033[01m"
 fi
 
-echo
-echo $E "${GREEN}KeyChain ${version}; ${BLUE}http://www.gentoo.org/projects/keychain${OFF}"
-echo $E " Copyright 2001 Gentoo Technologies, Inc.; Distributed under the GPL" 
+quiet_mode="no"
+if [ -n "`echo $* | grep '\-\-quiet'`" ] || [ -n "`echo $* | grep '\-q'`" ] ;
+then
+	quiet_mode="yes"
+fi
+
+if [ "$quiet_mode" = "no" ]
+then
+	echo
+	echo $E "${GREEN}KeyChain ${version}; ${BLUE}http://www.gentoo.org/projects/keychain${OFF}"
+	echo $E " Copyright 2001 Gentoo Technologies, Inc.; Distributed under the GPL" 
+fi
 
 #This should work under Linux, BSD, others
 psopts="FAIL"
@@ -64,27 +81,30 @@ else
 fi
 if [ "$psopts" = "FAIL" ]
 then
-	echo $0: unable to use \"ps\" to scan for ssh-agent processes.  Report KeyChain version and
+	echo $0: unable to use \"ps\" to scan for ssh-agent processes.  Report keychain version and
 	echo system configuration to drobbins@gentoo.org.
+	rm -f "${lockf}" 2> /dev/null
 	exit 1
 fi
 
 
 mypids=`ps $psopts 2>/dev/null | grep "[s]sh-agent" | awk '{print $2}'` > /dev/null 2>&1
 
-if [ -n "`echo $* | grep '\-\-stop'`" ]
+if [ -n "`echo $* | grep '\-\-stop'`" ] || [ -n "`echo $* | grep '\-k'`" ]
 then
 	# --stop tells keychain to kill the existing ssh-agent(s), then exit
 	kill $mypids > /dev/null 2>&1
- 	kill -9 $mypids > /dev/null 2>&1
- 	rm -f ${pidf} ${cshpidf} 2> /dev/null
+	rm -f "${pidf}" "${cshpidf}" "$lockf" 2> /dev/null
 	#`whoami` (rather than the $LOGNAME var) gives us the euid rather than the uid (what we want)
-	echo $E " ${GREEN}*${OFF} All ssh-agent(s) started by" `whoami` "are now stopped."
-	echo
+	if [ "$quiet_mode" = "no" ]
+	then
+		echo $E " ${GREEN}*${OFF} All ssh-agent(s) started by" `whoami` "are now stopped."
+		echo
+	fi
 	exit 0
 fi
 
-if [ -n "`echo $* | grep '\-\-help'`" ]
+if [ -n "`echo $* | grep '\-h'`" ]
 then
 echo $E Usage: ${CYAN}${0}${OFF} [ ${GREEN}options${OFF} ] ${CYAN}sshkey${OFF} ...
 cat <<EOHELP
@@ -152,14 +172,21 @@ echo $E " ${GREEN}--nocolor${OFF}"
 echo
 echo " This option disables color highlighting for non vt-100-compatible terms."
 echo
-echo $E " ${GREEN}--stop${OFF}"
+echo $E " ${GREEN}--stop | -k${OFF}"
 echo
 cat <<EOHELP
  This option tells keychain to stop all running ssh-agent processes, and then
  exit.
-
+EOHELP
+echo
+echo $E " ${GREEN}--quiet | -q${OFF}"
+echo
+cat <<EOHELP
+ This option tells keychain to turn off verbose mode and only print error
+ messages and interactive messages. This is useful for login scripts etc.
 EOHELP
 #' this line is a simple fix for vim syntax highlighting
+	rm -f "$lockf" 2> /dev/null
 	exit 1
 fi
 
@@ -176,7 +203,10 @@ for x in $mypids
 do
 	if [ "$x" = "$SSH_AGENT_PID" ]
 	then
-		echo $E " ${GREEN}*${OFF} Found existing ssh-agent at PID ${x}"
+		if [ "$quiet_mode" = "no" ]
+		then
+			echo $E " ${GREEN}*${OFF} Found existing ssh-agent at PID ${x}"
+		fi
 		match="yes"
 		break
 	fi
@@ -187,25 +217,30 @@ then
 	if [ -n "$mypids" ]
 	then
 		kill $mypids > /dev/null 2>&1
-		kill -9 $mypids > /dev/null 2>&1
 	fi
-	echo $E " ${GREEN}*${OFF} All previously running ssh-agent(s) have been stopped."
-	echo $E " ${GREEN}*${OFF} Initializing ${pidf} file..."
+	if [ "$quiet_mode" = "no" ]
+	then
+		echo $E " ${GREEN}*${OFF} All previously running ssh-agent(s) have been stopped."
+		echo $E " ${GREEN}*${OFF} Initializing ${pidf} file..."
+	fi
 	# "> pidf" doesn't work ash.  But it should work with any sh-compatible shell
-	> $pidf || { echo "$0: Cannot create ${pidf}; exiting." 1>&2; exit 1; }
-	echo $E " ${GREEN}*${OFF} Initializing ${cshpidf} file..."
-	> $cshpidf || { echo "$0: Cannot create ${cshpidf}; exiting." 1>&2; exit 1; }
-	chmod 0600 $pidf $cshpidf
-	echo $E " ${GREEN}*${OFF} Starting new ssh-agent"
-	nohup ssh-agent -s | grep -v 'Agent pid' > $pidf
-	. $pidf
-	echo "setenv SSH_AUTH_SOCK $SSH_AUTH_SOCK;" > $cshpidf
-	echo "setenv SSH_AGENT_PID $SSH_AGENT_PID;" >> $cshpidf
+	> "$pidf" || { echo "$0: Cannot create ${pidf}; exiting." 1>&2; rm -f "$pidf" "$cshpidf" "$lockf" 2> /dev/null; exit 1; }
+	[ "$quiet_mode" = "no" ] && echo $E " ${GREEN}*${OFF} Initializing ${cshpidf} file..."
+	> "$cshpidf" || { echo "$0: Cannot create ${cshpidf}; exiting." 1>&2; rm -f "$pidf" "$cshpidf" "$lockf" 2> /dev/null; exit 1; }
+	chmod 0600 "$pidf" "$cshpidf"
+	[ "$quiet_mode" = "no" ] && echo $E " ${GREEN}*${OFF} Starting new ssh-agent"
+	nohup ssh-agent -s | grep -v 'Agent pid' > "$pidf"
+	. "$pidf"
+	echo "setenv SSH_AUTH_SOCK $SSH_AUTH_SOCK;" > "$cshpidf"
+	echo "setenv SSH_AGENT_PID $SSH_AGENT_PID;" >> "$cshpidf"
 fi
+
+#unlock, now that ssh-agent is running
+rm -f "$lockf" 2> /dev/null
 
 if [ -n "`echo $* | grep '\-\-clear'`" ]
 then
-	echo -n $E " ${GREEN}*${OFF} "
+	echo $E " ${GREEN}*${OFF} \c"
 	ssh-add -D
 fi
 
@@ -220,7 +255,7 @@ then
 fi
 
 # hook in to existing agent
-. $pidf
+. "$pidf"
 
 missingkeys="START"
 myfail=0
@@ -254,7 +289,7 @@ do
 	then
 		break
 	fi
-	echo $E " ${GREEN}*${OFF} Adding ${BLUE}${missingkeys}${OFF}..."
+	[ "$quiet_mode" = "no" ] && echo $E " ${GREEN}*${OFF} Adding ${BLUE}${missingkeys}${OFF}..."
 	ssh-add ${missingkeys}
 	if [ $? -ne 0 ]
 	then
@@ -262,4 +297,7 @@ do
 		echo $E " ${CYAN}*${OFF} Problem adding key${OFF}..."
 	fi
 done
-echo
+if [ "$quiet_mode" = "no" ]
+then
+	echo
+fi
